import { useEffect, useState } from 'react'
import { MapContainer, Marker, TileLayer, Tooltip, useMap } from 'react-leaflet'
import L from 'leaflet'
import type { Crew, WorkOrder } from '../types'
import { isStale, statusMeta } from '../lib/domain'

function Focus({ order }: { order?: WorkOrder }) { const map = useMap(); useEffect(() => { if (order) map.flyTo([order.lat, order.lng], 15, { duration: .5 }) }, [map, order]); return null }
const crewIcon = (crew: Crew, stale: boolean) => L.divIcon({ className: 'vehicle-icon', iconSize: [58, 58], iconAnchor: [29, 29], html: `<div class="crew-marker ${stale ? 'crew-marker--stale' : ''}" title="${crew.nombre}"><span class="crew-marker__pulse"></span><span class="crew-marker__halo"></span><div class="crew-marker__vehicle" style="transform:rotate(${crew.heading}deg)"><svg viewBox="0 0 48 48" width="42" height="42" aria-hidden="true"><path fill="#1d4ed8" stroke="white" stroke-width="3" d="M13 17h22l5 10v12H8V27z"/><path fill="#dbeafe" d="M16 19h7v7h-10zm9 0h7l4 7h-11z"/><circle cx="15" cy="39" r="4" fill="#0f172a" stroke="white" stroke-width="2"/><circle cx="34" cy="39" r="4" fill="#0f172a" stroke="white" stroke-width="2"/><path d="M24 8l6 9H18z" fill="#facc15" stroke="white" stroke-width="1.5"/></svg></div></div>` })
const orderIcon = (order: WorkOrder, highlighted: boolean) => { const color = statusMeta[order.estado].color; return L.divIcon({ className: 'vehicle-icon', iconSize: [36, 42], iconAnchor: [18, 38], html: `<div class="order-marker ${highlighted ? 'order-marker--highlighted' : ''}" title="${order.cliente_nombre}">${highlighted ? '<span class="order-marker__pulse"></span><span class="order-marker__label">OT seleccionada</span>' : ''}<svg viewBox="0 0 48 54" width="36" height="42" aria-hidden="true"><path fill="${color}" stroke="white" stroke-width="2.5" d="M24 2C12 2 5 11 5 22c0 15 19 29 19 29s19-14 19-29C43 11 36 2 24 2z"/><circle cx="24" cy="18" r="6" fill="white"/><path d="M13 37c1-7 6-11 11-11s10 4 11 11" fill="white"/></svg></div>` }) }
export function MapView({ crews, orders, selectedOrder, highlightedOrderId, onCrew, onOrder }: { crews: Crew[]; orders: WorkOrder[]; selectedOrder?: WorkOrder; highlightedOrderId?: string; onCrew: (crew: Crew) => void; onOrder: (order: WorkOrder) => void }) {
  const [clock, setClock] = useState(Date.now())
  useEffect(() => { const timer = window.setInterval(() => setClock(Date.now()), 5_000); return () => window.clearInterval(timer) }, [])
  return <MapContainer center={[-16.5, -68.145]} zoom={12} scrollWheelZoom><TileLayer attribution="&copy; OpenStreetMap contributors" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" /><Focus order={selectedOrder} />{crews.map(c => { const stale = isStale(c.ultima_actualizacion, clock); return <Marker key={c.id} position={[c.lat, c.lng]} icon={crewIcon(c, stale)} eventHandlers={{ click: () => onCrew(c) }}><Tooltip direction="top">{c.nombre}{stale ? ' · señal vencida' : ''}</Tooltip></Marker> })}{orders.map(o => { const highlighted = o.id === highlightedOrderId; return <Marker key={o.id} position={[o.lat, o.lng]} icon={orderIcon(o, highlighted)} zIndexOffset={highlighted ? 1_000 : 0} eventHandlers={{ click: () => onOrder(o) }}><Tooltip>{o.codigo_ot} · {statusMeta[o.estado].label}</Tooltip></Marker> })}</MapContainer>
}
