-- Run with `supabase db push` after linking a project. This app never uses a service-role key.
create extension if not exists postgis;

create table public.roles (id uuid primary key default gen_random_uuid(), nombre varchar(50) not null unique check (nombre in ('admin','coordinador','tecnico')), descripcion text);
insert into public.roles (nombre, descripcion) values ('admin','Supervisor'),('coordinador','Gestión operativa'),('tecnico','Técnico de campo');
create table public.users (id uuid primary key references auth.users(id) on delete cascade, role_id uuid not null references public.roles(id), nombre_completo varchar(150) not null, email varchar(150) not null unique, telefono varchar(30), activo boolean not null default true, created_at timestamptz not null default now());
create table public.cuadrillas (id uuid primary key default gen_random_uuid(), nombre varchar(100) not null, placa_vehiculo varchar(20), tecnico_1_id uuid references public.users(id), tecnico_2_id uuid references public.users(id), posicion_actual geometry(Point,4326), heading float not null default 0 check (heading >= 0 and heading <= 360), estado_operativo varchar(30) not null default 'inactivo' check (estado_operativo in ('activo','inactivo','sin_senal')), ultima_actualizacion timestamptz);
create table public.ordenes_trabajo (id uuid primary key default gen_random_uuid(), codigo_ot varchar(30) not null unique, cliente_nombre varchar(150) not null, cliente_telefono varchar(30), ubicacion_cliente geometry(Point,4326) not null, direccion_referencial text, tipo_tarea varchar(50) not null, estado varchar(30) not null default 'pendiente' check (estado in ('pendiente','en_camino','en_sitio','finalizado','suspendido')), cuadrilla_id uuid references public.cuadrillas(id), fecha_programada date not null, motivo_postergacion text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check ((estado = 'suspendido' and motivo_postergacion is not null and length(trim(motivo_postergacion)) > 0) or estado <> 'suspendido'));
create table public.historial_ubicaciones (id uuid primary key default gen_random_uuid(), cuadrilla_id uuid not null references public.cuadrillas(id), ot_id uuid references public.ordenes_trabajo(id), posicion geometry(Point,4326) not null, heading float check (heading >= 0 and heading <= 360), velocidad float check (velocidad is null or velocidad >= 0), registrado_en timestamptz not null default now());
create index idx_cuadrillas_posicion on public.cuadrillas using gist(posicion_actual); create index idx_ot_ubicacion on public.ordenes_trabajo using gist(ubicacion_cliente); create index idx_historial_posicion on public.historial_ubicaciones using gist(posicion); create index idx_historial_cuadrilla_fecha on public.historial_ubicaciones(cuadrilla_id, registrado_en); create index idx_ot_fecha_estado on public.ordenes_trabajo(fecha_programada, estado);
create function public.set_updated_at() returns trigger language plpgsql set search_path = public as $$ begin new.updated_at = now(); return new; end; $$;
create trigger ordenes_updated_at before update on public.ordenes_trabajo for each row execute function public.set_updated_at();
create function public.enforce_technician_crew_update() returns trigger language plpgsql set search_path = public as $$ begin if public.current_user_role() = 'tecnico' and (new.nombre is distinct from old.nombre or new.placa_vehiculo is distinct from old.placa_vehiculo or new.tecnico_1_id is distinct from old.tecnico_1_id or new.tecnico_2_id is distinct from old.tecnico_2_id) then raise exception 'Technicians may only report location'; end if; return new; end; $$;
create trigger crew_technician_restriction before update on public.cuadrillas for each row execute function public.enforce_technician_crew_update();
-- These helpers must bypass table RLS to avoid policy recursion. They expose only the caller's role/membership,
-- lock their search_path, and are callable solely by authenticated users.
create function public.current_user_role() returns varchar language sql stable security definer set search_path = public as $$ select r.nombre from public.users u join public.roles r on r.id=u.role_id where u.id=(select auth.uid()) and u.activo $$;
create function public.is_own_crew(crew uuid) returns boolean language sql stable security definer set search_path = public as $$ select exists(select 1 from public.cuadrillas c where c.id=crew and (c.tecnico_1_id=(select auth.uid()) or c.tecnico_2_id=(select auth.uid()))) $$;
revoke all on function public.current_user_role() from public; revoke all on function public.is_own_crew(uuid) from public; grant execute on function public.current_user_role(), public.is_own_crew(uuid) to authenticated;
grant usage on schema public to authenticated; grant select, insert, update, delete on public.users, public.cuadrillas, public.ordenes_trabajo, public.historial_ubicaciones to authenticated; grant select on public.roles to authenticated;
alter table public.roles enable row level security; alter table public.users enable row level security; alter table public.cuadrillas enable row level security; alter table public.ordenes_trabajo enable row level security; alter table public.historial_ubicaciones enable row level security;
create policy roles_read on public.roles for select to authenticated using (true);
create policy users_read on public.users for select to authenticated using (public.current_user_role() in ('admin','coordinador') or id=(select auth.uid())); create policy users_self_update on public.users for update to authenticated using (id=(select auth.uid())) with check (id=(select auth.uid()) and role_id=(select role_id from public.users where id=(select auth.uid())));
create policy crews_read on public.cuadrillas for select to authenticated using (public.current_user_role() in ('admin','coordinador') or public.is_own_crew(id)); create policy crews_admin_write on public.cuadrillas for all to authenticated using (public.current_user_role()='admin') with check (public.current_user_role()='admin'); create policy crews_tech_position on public.cuadrillas for update to authenticated using (public.current_user_role()='tecnico' and public.is_own_crew(id)) with check (public.current_user_role()='tecnico' and public.is_own_crew(id));
create policy orders_read on public.ordenes_trabajo for select to authenticated using (public.current_user_role() in ('admin','coordinador') or public.is_own_crew(cuadrilla_id)); create policy orders_manage on public.ordenes_trabajo for all to authenticated using (public.current_user_role() in ('admin','coordinador')) with check (public.current_user_role() in ('admin','coordinador'));
create policy history_read on public.historial_ubicaciones for select to authenticated using (public.current_user_role() in ('admin','coordinador')); create policy history_tech_insert on public.historial_ubicaciones for insert to authenticated with check (public.current_user_role()='tecnico' and public.is_own_crew(cuadrilla_id));
alter publication supabase_realtime add table public.cuadrillas, public.ordenes_trabajo;
create view public.dashboard_crews with (security_invoker=true) as select c.*, st_y(c.posicion_actual) as lat, st_x(c.posicion_actual) as lng, u1.nombre_completo as tecnico_1_nombre, u2.nombre_completo as tecnico_2_nombre from public.cuadrillas c left join public.users u1 on u1.id=c.tecnico_1_id left join public.users u2 on u2.id=c.tecnico_2_id;
create view public.dashboard_orders with (security_invoker=true) as select o.*, st_y(o.ubicacion_cliente) as lat, st_x(o.ubicacion_cliente) as lng from public.ordenes_trabajo o;
grant select on public.dashboard_crews, public.dashboard_orders to authenticated;
